# Generated by Django 5.0.2 on 2024-03-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.IntegerField()),
                ('claim_type', models.IntegerField()),
                ('claim_desc', models.CharField(max_length=200)),
                ('claim_date', models.DateField()),
                ('claim_photo', models.ImageField(upload_to=None)),
                ('repair_status', models.IntegerField()),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_app.sale')),
            ],
        ),
    ]
