# Generated by Django 4.2.9 on 2024-03-27 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_type', models.IntegerField()),
                ('claim_desc', models.CharField(max_length=200)),
                ('claim_date', models.DateField()),
                ('decision_date', models.DateField(null=True)),
                ('claim_photo', models.ImageField(upload_to='images/')),
                ('claim_status', models.IntegerField(default=0)),
                ('deciding_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_app.sale')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimRepair',
            fields=[
                ('repair_id', models.AutoField(primary_key=True, serialize=False)),
                ('repair_desc', models.CharField(max_length=200, null=True)),
                ('repair_date', models.DateField(null=True)),
                ('repair_photo', models.ImageField(null=True, upload_to='images/')),
                ('repair_status', models.IntegerField(default=1)),
                ('claim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims_app.claim')),
                ('repair_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
