# Generated by Django 5.0.2 on 2024-03-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_status',
            field=models.IntegerField(default=0),
        ),
    ]
