# Generated by Django 5.0.2 on 2024-03-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims_app', '0002_claim_claim_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='id',
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
