# Generated by Django 4.2.11 on 2024-03-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims_app', '0004_alter_claim_claim_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='sale_id',
            field=models.IntegerField(),
        ),
    ]
