# Generated by Django 4.2.11 on 2024-03-26 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0004_remove_sale_id_alter_sale_sale_id'),
        ('claims_app', '0005_alter_claim_sale_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_app.sale'),
        ),
    ]
