# Generated by Django 4.2.11 on 2024-03-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims_app', '0005_remove_claim_repair_status_claim_decision_date_and_more'),
        ('claims_app', '0006_alter_claim_sale_id'),
    ]

    operations = [
    ]
