# Generated by Django 4.2.11 on 2024-03-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='digital_signature',
        ),
        migrations.AddField(
            model_name='sale',
            name='product_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
