# Generated by Django 4.2.11 on 2024-03-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_remove_sale_digital_signature_sale_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='digital_signature',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
