# Generated by Django 4.2.11 on 2024-03-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0003_sale_digital_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id',
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
